# -*- coding: utf-8 -*-
"""kdramaRecommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GtL8u5ydaS7Ynzqpyz9XXT-UvE4rvxGa

Tutorial: https://thecleverprogrammer.com/2022/07/05/netflix-recommendation-system-using-python/

Import Libraries
"""

import numpy as np
import pandas as pd
from sklearn.feature_extraction import text
from sklearn.metrics.pairwise import cosine_similarity

data = pd.read_csv("/content/top100_kdrama.csv")
print(data.head())

"""Data Cleaning"""

print(data.isnull().sum())

data = data[["Name", "Synopsis", "Cast", "Year of release", "Genre", "Rating"]]
print(data.head())

data = data.dropna()

import nltk
import re
nltk.download('stopwords')
stemmer = nltk.SnowballStemmer("english")
from nltk.corpus import stopwords
import string
stopword=set(stopwords.words('english'))

def clean(text):
    text = str(text).lower()

    return text
data["Name"] = data["Name"].apply(clean)

print(data.Name.sample(10))

feature = data["Year of release"].tolist()
tfidf = text.TfidfVectorizer(input='content', stop_words="english") # Change input to 'content'
tfidf_matrix = tfidf.fit_transform(feature)
similarity = cosine_similarity(tfidf_matrix)

'''feature = data["Genre"].tolist()
tfidf = text.TfidfVectorizer(input=feature, stop_words="english")
tfidf_matrix = tfidf.fit_transform(feature)
similarity = cosine_similarity(tfidf_matrix)'''

indices = pd.Series(data.index,
                    index=data['Name']).drop_duplicates()

def recommend_kdrama(name, similarity = similarity):
    index = indices[name]
    similarity_scores = list(enumerate(similarity[index]))
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
    similarity_scores = similarity_scores[0:10]
    kdrama_indices = [i[0] for i in similarity_scores]
    return data['Name'].iloc[kdrama_indices]

print(recommend_kdrama("hotel del luna"))